#!/usr/bin/env bash

# Configure local admin kubeconfig
cd target
. admin-activate.sh

# Install kubernetes-dashboard	
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0/aio/deploy/recommended.yaml

# create admin token for kubernetes-dashboard
# https://superuser.com/questions/1394619/how-to-get-the-admin-user-token-from-kubectl
kubectl create serviceaccount admin -n kube-system
kubectl create clusterrolebinding admin --clusterrole=cluster-admin --serviceaccount=kube-system:admin
echo 'your kubernetes-dashboard admin token is: '
kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep ^admin-token- | awk '{print $1}') | grep ^token: | awk '{print $2}'
# start port-forwarding for kubernetes-dashboard
#     kubectl -n kubernetes-dashboard port-forward $(kubectl -n kubernetes-dashboard get pods | grep ^kubernetes-dashboard- | awk '{print $1}') 8443:8443

# install nginx ingress controller
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm install my-ingress ingress-nginx/ingress-nginx
