---
- connection: local
  delegate_to: localhost
  run_once: yes
  become: no
  block:

    - set_fact:
        local_ca_cert_dir: '{{playbook_dir}}/target/cert/ca'
      
    - name: 'ensure dir cert/ca exist'
      file: 
        path: '{{local_ca_cert_dir}}'
        state: directory
        recurse: yes

    - name: generate central authority certificate and key localy
      command:
        argv:
          - openssl
          - req
          - -x509
          - -newkey
          - 'rsa:{{rsa_key_size}}'
          - -keyout
          - '{{local_ca_cert_dir}}/key.pem'
          - -out 
          - '{{local_ca_cert_dir}}/cert.pem'
          - -days
          - 9999
          - -nodes
          - -subj
          - '/CN={{common_name}}/C={{country_name}}/L={{locality}}/O={{organization}}/OU={{organizational_unit}}/ST={{state_of_residence}}'
          # без basicConstraints в подписанные этим корневым сертфикатом сертификаты не прописываются хосты
          - -addext
          - basicConstraints=critical,CA:TRUE,pathlen:3
        creates: '{{local_ca_cert_dir}}/key.pem'